# Simulation
simulation:         True

# stateMachine.py
desiredDistance:    2
distanceInverted:   False
rotationInverted:   True
forwardSpeed:       0.5

# pointCloudSampler.py
n_samples:          5

# fenceDetector.py
init_dist:          2
init_ang:           0
min_dist_x:         1.1
max_dist_x:         6
height_thres:       -0.7
min_fence_points:   50
lp_alpha_dist:      0.1
lp_alpha_ang:       0.1
