# Simulation
simulation:         True

# stateMachine.py
desiredDistance:            2
distanceInverted:           False
rotationInverted:           True
forwardSpeed:               0.5
timeToWaitForFenceSample:   0.5

# pointCloudSampler.py
n_samples:                  3

# fenceDetector.py
init_dist:          2
init_ang:           0
min_dist_x:         1.1
max_dist_x:         6
height_thresh:      0.5
min_fence_points:   50
lp_alpha_dist:      0.5 
lp_alpha_ang:       0.1
min_r2_fence:       0.2
